### ISSUE TITLE
get the textfield.text 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [amirdew/AMLoginSignup#2]
I'm afraid if my question sounds silly but I want to know how to get the output of "email" and "password"? usually It's got by " email.text = "leo" or if password.text != nil {} 

how about in here ?

**Comment by amirdew** [comment]
You can access UITextField by adding IBOutlet for inputViews
[changes](https://github.com/amirdew/AMLoginSignup/commit/09fe37957980779093cb31a1dd43ce9a0771db08)
